import type { FormDefinition, FormField, FormPage, SelectOption } from '@/src/core/form/types';
import { DURATION_DAYS_KEY } from '@/src/core/form/types';

function yesNo(workFactor: number, materialFactor: number): SelectOption[] {
  return [
    { label: 'Kyllä', value: 'kylla', workFactor, materialFactor },
    { label: 'Ei', value: 'ei', workFactor: 1, materialFactor: 1 },
  ];
}

function field(partial: Omit<FormField, 'required' | 'showOnSummary'> & Partial<FormField>): FormField {
  return {
    required: false,
    showOnSummary: true,
    ...partial,
  };
}

/**
 * Referenssipohja PDF:n ulkoverhous- / maalaustyölomakkeelle.
 * Esimerkkikaava: (120 - 18) * 1,15 = 117,30 m²
 */
export function createCladdingFormDefinition(): FormDefinition {
  const pages: FormPage[] = [
    { id: 'page_customer', title: 'Asiakas', sortOrder: 0, system: 'customer' },
    { id: 'page_surfaces', title: 'Pinta-alat', sortOrder: 1 },
    { id: 'page_eaves', title: 'Räystäs ja alakatto', sortOrder: 2 },
    { id: 'page_extras', title: 'Lisäosat', sortOrder: 3 },
    { id: 'page_paint', title: 'Maali', sortOrder: 4 },
    { id: 'page_phases', title: 'Työvaiheet', sortOrder: 5 },
    { id: 'page_duration', title: 'Työryhmän arvioitu kesto (pv)', sortOrder: 6 },
    { id: 'page_materials', title: 'Materiaalit', sortOrder: 7, system: 'materials' },
  ];

  const fields: FormField[] = [
    field({
      id: 'cl_kiinteä',
      pageId: 'page_surfaces',
      key: 'kiinteä_seinäpinta_ala_m2',
      label: 'Kiinteä seinäpinta-ala',
      type: 'number',
      sortOrder: 0,
      required: true,
      unit: 'm²',
      debugExampleValue: '120',
    }),
    field({
      id: 'cl_laudoitus',
      pageId: 'page_surfaces',
      key: 'laudoitustyyppi',
      label: 'Laudoitustyyppi',
      type: 'select',
      sortOrder: 1,
      required: true,
      debugExampleValue: 'paneeli',
      options: [
        { label: 'Paneeli', value: 'paneeli', multiplier: 1.15, exportKey: 'laudoituskerroin' },
        { label: 'Lomalaudoitus', value: 'lomalaudoitus', multiplier: 1.25, exportKey: 'laudoituskerroin' },
        { label: 'Rimalaudoitus', value: 'rimalaudoitus', multiplier: 1.3, exportKey: 'laudoituskerroin' },
        { label: 'Hirsi', value: 'hirsi', multiplier: 1.0, exportKey: 'laudoituskerroin' },
      ],
    }),
    field({
      id: 'cl_aukot',
      pageId: 'page_surfaces',
      key: 'aukkovähennykset',
      label: 'Aukkovähennykset',
      type: 'number',
      sortOrder: 2,
      unit: 'm²',
      debugExampleValue: '18',
    }),
    field({
      id: 'cl_ikkunat',
      pageId: 'page_surfaces',
      key: 'ikkunat_lkm',
      label: 'Ikkunat (lkm)',
      type: 'number',
      sortOrder: 3,
      unit: 'kpl',
      debugExampleValue: '3',
    }),
    field({
      id: 'cl_ovet',
      pageId: 'page_surfaces',
      key: 'ovet_lkm',
      label: 'Ovet (lkm)',
      type: 'number',
      sortOrder: 4,
      unit: 'kpl',
      debugExampleValue: '2',
    }),
    field({
      id: 'cl_aukko_laskettu',
      pageId: 'page_surfaces',
      key: 'aukko_laskettu_m2',
      label: 'Aukot oletusmitoilla',
      type: 'computed',
      sortOrder: 5,
      showOnSummary: false,
      unit: 'm²',
      formula:
        'ikkunat_lkm * defaults.ikkuna_leveys_m * defaults.ikkuna_korkeus_m + ovet_lkm * defaults.ovi_leveys_m * defaults.ovi_korkeus_m',
    }),
    field({
      id: 'cl_seinä',
      pageId: 'page_surfaces',
      key: 'laskenta_seinäpinta_ala_m2',
      label: 'Seinäpinta-ala (laskettu)',
      type: 'computed',
      sortOrder: 6,
      unit: 'm²',
      formula: '(kiinteä_seinäpinta_ala_m2 - aukkovähennykset) * laudoituskerroin',
    }),
    field({
      id: 'cl_räystäs_m',
      pageId: 'page_eaves',
      key: 'räystäsmetrit_m',
      label: 'Räystäsmetrit',
      type: 'number',
      sortOrder: 0,
      unit: 'm',
      debugExampleValue: '20',
    }),
    field({
      id: 'cl_räystäs_tyyppi',
      pageId: 'page_eaves',
      key: 'räystästyyppi',
      label: 'Räystästyyppi',
      type: 'select',
      sortOrder: 1,
      debugExampleValue: 'avo',
      options: [
        { label: 'Avo', value: 'avo', multiplier: 1, exportKey: 'räystäskerroin' },
        { label: 'Umpi', value: 'umpi', multiplier: 1.3, exportKey: 'räystäskerroin' },
      ],
    }),
    field({
      id: 'cl_räystäs_ala',
      pageId: 'page_eaves',
      key: 'räystäspinta_ala',
      label: 'Räystäspinta-ala',
      type: 'computed',
      sortOrder: 2,
      unit: 'm²',
      formula: 'räystäsmetrit_m * räystäskerroin * defaults.räystään_leveys_m',
    }),
    field({
      id: 'cl_alakatto',
      pageId: 'page_eaves',
      key: 'alakattoneliöt_m2',
      label: 'Alakattoneliöt',
      type: 'number',
      sortOrder: 3,
      unit: 'm²',
      debugExampleValue: '10',
    }),
    field({
      id: 'cl_kestolisä',
      pageId: 'page_extras',
      key: 'työnkestolisä',
      label: 'Työnkestolisä',
      type: 'number',
      sortOrder: 0,
      showOnSummary: false,
      unit: 'h',
      effects: [{ type: 'add_duration', amountRef: 'työnkestolisä' }],
    }),
    field({
      id: 'cl_matlisä',
      pageId: 'page_extras',
      key: 'materiaalilisä',
      label: 'Materiaalilisä',
      type: 'number',
      sortOrder: 1,
      showOnSummary: false,
      unit: '€',
      effects: [{ type: 'add_material_fixed', amountRef: 'materiaalilisä' }],
    }),
    field({
      id: 'cl_lista',
      pageId: 'page_extras',
      key: 'listalaudat_valinta',
      label: 'Listalaudat',
      type: 'select',
      sortOrder: 2,
      options: yesNo(1.05, 1.05),
    }),
    field({
      id: 'cl_nurkka',
      pageId: 'page_extras',
      key: 'nurkkalaudat_valinta',
      label: 'Nurkkalaudat',
      type: 'select',
      sortOrder: 3,
      options: yesNo(1.08, 1.08),
    }),
    field({
      id: 'cl_maali',
      pageId: 'page_paint',
      key: 'kautettavamaali',
      label: 'Kautettava maali',
      type: 'product_select',
      sortOrder: 0,
      showOnSummary: false,
    }),
    field({
      id: 'cl_sävyt',
      pageId: 'page_paint',
      key: 'savyjen_lukumaara',
      label: 'Sävyjen lukumäärä',
      type: 'number',
      sortOrder: 1,
      unit: 'kpl',
    }),
    field({
      id: 'cl_väri',
      pageId: 'page_paint',
      key: 'varinvaihto_valinta',
      label: 'Värinvaihto',
      type: 'boolean',
      sortOrder: 2,
    }),
    field({
      id: 'cl_maara',
      pageId: 'page_paint',
      key: 'materiaali_maara',
      label: 'Maalin määrä',
      type: 'computed',
      sortOrder: 3,
      unit: 'l',
      formula: 'laskenta_seinäpinta_ala_m2 / kautettavamaali.consumption',
      effects: [
        {
          type: 'add_material',
          productRef: 'kautettavamaali',
          quantityRef: 'materiaali_maara',
        },
      ],
    }),
    field({
      id: 'cl_home',
      pageId: 'page_phases',
      key: 'markahomepesu_valinta',
      label: 'Markahomepesu',
      type: 'select',
      sortOrder: 0,
      options: yesNo(1.1, 1.05),
    }),
    field({
      id: 'cl_homeeste',
      pageId: 'page_phases',
      key: 'homeenestokasittely_valinta',
      label: 'Homeenestokäsittely',
      type: 'select',
      sortOrder: 1,
      options: yesNo(1.1, 1.1),
    }),
    field({
      id: 'cl_poisto',
      pageId: 'page_phases',
      key: 'maalinpoisto_valinta',
      label: 'Maalinpoisto',
      type: 'select',
      sortOrder: 2,
      options: yesNo(1.25, 1.15),
    }),
    field({
      id: 'cl_pohja',
      pageId: 'page_phases',
      key: 'pohjamaalaus_valinta',
      label: 'Pohjamaalaus',
      type: 'select',
      sortOrder: 3,
      options: yesNo(1.15, 1.2),
    }),
    field({
      id: 'cl_duration',
      pageId: 'page_duration',
      key: DURATION_DAYS_KEY,
      label: 'Kesto',
      type: 'number',
      sortOrder: 0,
      required: true,
      unit: 'pv',
      debugExampleValue: '5',
    }),
  ];

  return {
    id: 'cladding',
    name: 'Ulkoverhous',
    version: 1,
    pages,
    fields,
    updatedAt: Date.now(),
  };
}
